### ISSUE TITLE
MAMutableArray tests against wrong class?

### ISSUE THREAD

**Issue by grgcombs** [mikeash/MACollections#1]
Hey Mike,

I absolutely love your "Let's Build..." series, and can't get enough of your articles.  When reading through the MAMutableArray implementation, it looks like the tests at the bottom are set to run against the built-in NSMutableArray implementation instead the DIY class.

**Comment by mikeash** [comment]
Thanks for letting me know. It's been a long time so I don't remember why that would have happened, but I updated it to fix that. Fortunately the tests still pass!
